Rover:

  # Position Controllers ---------------------------------------
  joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: sonar_front_joint
    pid: {p: 0.5, i: 0.0001, d: 10}