Rover:

  # Position Controllers ---------------------------------------
  joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: sonar_front_joint
    pid: {p: 1.0, i: 0.0, d: 0.0}